services:
  frontend:
    image: "frontend:latest"
    ports:
     - 8000:80
  backend:
    image: "backend:latest"
    ports:
      - 9000:9000
    environment:
      - SKYPEDAL_PROFILE=prod
      - SKYPEDAL_SPRING_PORT=9000
      - MAPS_API_TOKEN
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=skypedal
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
