services:
  frontend:
    depends_on:
      - backend
    image: "frontend:latest"
    ports:
     - 8000:80
  backend:
    depends_on:
      - mysql
    image: "backend:latest"
    ports:
      - 9000:9000
    environment:
      - SKYPEDAL_PROFILE=prod
      - SKYPEDAL_SPRING_PORT=9000
      - MAPS_API_TOKEN
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=skypedal
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/live/skypedal.moolman.dev/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./certbot/conf/live/skypedal.moolman.dev/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - frontend
      - backend
  certbot:
    profiles: ["certbot"]
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
